apiVersion: kasmcloud.io/v1alpha1
kind: Provider
metadata:
  name: httpserver-default
spec:
  host: default
  link: test
  #  Image pull is faster, you can use `wasmcloud.azurecr.io/httpserver:0.17.0`
  image: ghcr.io/iceber/wasmcloud/httpserver:0.17.0-index
---
apiVersion: kasmcloud.io/v1alpha1
kind: Actor
metadata:
  name: echo-default
spec:
  host: default
  image: wasmcloud.azurecr.io/echo:0.3.8
  replicas: 10
---
apiVersion: kasmcloud.io/v1alpha1
kind: Link
metadata:
  name: httpserver-echo
spec:
  contractId: "wasmcloud:httpserver"
  actor:
    name: echo-default
  provider:
    name: httpserver-default
  values:
    address: "0.0.0.0:8080"
