apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kasmcloud-host
  name: kasmcloud-temporary-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasmcloud-host
      kasmcloud-host/type: temporary
  template:
    metadata:
      labels:
        app: kasmcloud-host
        kasmcloud-host/type: temporary
    spec:
      containers:
      - command:
        - "/usr/local/bin/kasmcloud"
        image: ghcr.io/iceber/kasmcloud/host:v0.0.2
        name: host
        env:
        - name: KASMCLOUD_TEMPORARY
          value: true
        - name: KASMCLOUD_NATS_URL
          value: "nats://kasmcloud-nats.default:4222"
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      serviceAccountName: kasmcloud-host
